spring.application.name=ImagineBanking
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.mode=HTML

spring.datasource.url=jdbc:postgresql://localhost:5432/ImaginaryBanking
spring.datasource.username=postgres
spring.datasource.password=ilovejesse
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
